BEGIN TRANSACTION;

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Normal',
        '1',
        '2',
        '1',
        '1',
        '1',
        '1',
        '1',
        '0',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Fighting',
        '1',
        '1',
        '2',
        '1',
        '1',
        '0.5',
        '0.5',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '2',
        '1',
        '1',
        '0.5',
        '2'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Flying',
        '1',
        '0.5',
        '1',
        '1',
        '0',
        '2',
        '0.5',
        '1',
        '1',
        '1',
        '1',
        '0.5',
        '2',
        '1',
        '2',
        '1',
        '1',
        '1'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Poison',
        '1',
        '0.5',
        '1',
        '0.5',
        '2',
        '1',
        '0.5',
        '1',
        '1',
        '1',
        '1',
        '0.5',
        '1',
        '2',
        '1',
        '1',
        '1',
        '0.5'
);
INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Ground',
        '1',
        '1',
        '1',
        '0.5',
        '1',
        '0.5',
        '1',
        '1',
        '1',
        '1',
        '2',
        '2',
        '0',
        '1',
        '2',
        '1',
        '1',
        '1'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Rock',
        '0.5',
        '2',
        '0.5',
        '0.5',
        '2',
        '1',
        '1',
        '1',
        '2',
        '0.5',
        '2',
        '2',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Bug',
        '1',
        '0.5',
        '2',
        '1',
        '0.5',
        '2',
        '1',
        '1',
        '1',
        '2',
        '1',
        '0.5',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Ghost',
        '0',
        '0',
        '1',
        '0.5',
        '1',
        '1',
        '0.5',
        '2',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '1',
        '2',
        '1'
);

INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
VALUES ('Steel',
        '0.5',
        '2',
        '0.5',
        '0',
        '2',
        '0.5',
        '0.5',
        '1',
        '0.5',
        '2',
        '1',
        '0.5',
        '1',
        '0.5',
        '0.5',
        '0.5',
        '1',
        '0.5'
);
 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Fire',
         '1',
         '1',
         '1',
         '1',
         '2',
         '2',
         '0.5',
         '1',
         '0.5',
         '0.5',
         '2',
         '0.5',
         '1',
         '1',
         '0.5',
         '1',
         '1',
         '0.5'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Water',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '0.5',
         '0.5',
         '0.5',
         '2',
         '2',
         '1',
         '0.5',
         '1',
         '1',
         '1'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Grass',
         '1',
         '1',
         '2',
         '2',
         '0.5',
         '1',
         '2',
         '1',
         '1',
         '2',
         '0.5',
         '0.5',
         '0.5',
         '1',
         '2',
         '1',
         '1',
         '1'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Electric',
         '1',
         '1',
         '0.5',
         '1',
         '2',
         '1',
         '1',
         '1',
         '0.5',
         '1',
         '1',
         '1',
         '0.5',
         '1',
         '1',
         '1',
         '1',
         '1'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Psychic',
         '1',
         '0.5',
         '1',
         '1',
         '1',
         '1',
         '2',
         '2',
         '1',
         '1',
         '1',
         '1',
         '1',
         '0.5',
         '1',
         '1',
         '2',
         '1'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Ice',
         '1',
         '2',
         '1',
         '1',
         '1',
         '2',
         '1',
         '1',
         '2',
         '2',
         '1',
         '1',
         '1',
         '1',
         '0.5',
         '1',
         '1',
         '1'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Dragon',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '0.5',
         '0.5',
         '0.5',
         '0.5',
         '1',
         '2',
         '2',
         '1',
         '2'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Dark',
         '1',
         '2',
         '1',
         '1',
         '1',
         '1',
         '2',
         '0.5',
         '1',
         '1',
         '1',
         '1',
         '1',
         '0',
         '1',
         '1',
         '0.5',
         '2'
 );

 INSERT INTO pokemon_types (type_name, normal_effectiveness, fighting_effectiveness, flying_effectiveness, poison_effectiveness, ground_effectiveness, rock_effectiveness, bug_effectiveness, ghost_effectiveness, steel_effectiveness, fire_effectiveness, water_effectiveness, grass_effectiveness, electric_effectiveness, psychic_effectiveness, ice_effectiveness, dragon_effectiveness, dark_effectiveness, fairy_effectiveness)
 VALUES ('Fairy',
         '1',
         '0.5',
         '1',
         '2',
         '1',
         '1',
         '0.5',
         '1',
         '2',
         '1',
         '1',
         '1',
         '1',
         '1',
         '1',
         '0',
         '0.5',
         '1'
 );

 COMMIT TRANSACTION;
